import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SignIn from '@/components/SignIn'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <title>UNIVERSITY OF WOLLONGONG AUSTRALIA </title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-shorthand-horizontal.png" />
      </Head>
      <SignIn/>
    </>
  )
}
