import SignUp from '@/components/SignUp'
import React from 'react'
import Head from 'next/head'
const signup = () => {
  return (
    <div>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <title>UNIVERSITY OF WOLLONGONG AUSTRALIA </title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="https://ik.imagekit.io/cmef8hxb6/index-removebg-preview_suXjc1Vcu.png?updatedAt=1679305145518" />
    </Head>
    <SignUp/>
    </div>
  )
}

export default signup
