import SignUp from '@/components/SignUp'
import React from 'react'
import Head from 'next/head'
const signup = () => {
  return (
    <div>
    <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <title>UNIVERSITY OF WOLLONGONG AUSTRALIA </title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="https://uowplaybook.s3-ap-southeast-2.amazonaws.com/logo/logo-shorthand-horizontal.png" />
    </Head>
    <SignUp/>
    </div>
  )
}

export default signup
